name: Deploy to Production VPS
on:
  push:
    branches:
      # 1. SE CAMBIÓ LA RAMA A "main"
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Clona el repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
      # Se conecta a tu VPS y ejecuta los comandos de despliegue
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/WhatsBotAdivisor
            git clone -b main https://github.com/1608-EQUIPOSISTEMAS/WhatsBotAdivisor.git ~/WhatsBotAdivisor
            cd ~/WhatsBotAdivisor
            npm install
            pm2 restart whats-bot